// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Example.proto
package protobuf;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(Example.extendData);
  }
  public interface BaseDataOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<BaseData> {

    // required int32 code = 1;
    /**
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     */
    int getCode();
  }
  /**
   * Protobuf type {@code BaseData}
   *
   * <pre>
   * ����һ��message BaseData��100~199֮���tag�ɹ���չ  
   * </pre>
   */
  public static final class BaseData extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        BaseData> implements BaseDataOrBuilder {
    // Use BaseData.newBuilder() to construct.
    private BaseData(com.google.protobuf.GeneratedMessage.ExtendableBuilder<Example.BaseData, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseData defaultInstance;
    public static BaseData getDefaultInstance() {
      return defaultInstance;
    }

      @Override
      public BaseData getDefaultInstanceForType() {
          return defaultInstance;
      }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Example.internal_static_BaseData_descriptor;
    }

      @Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
          return Example.internal_static_BaseData_fieldAccessorTable
                  .ensureFieldAccessorsInitialized(
                          Example.BaseData.class, Example.BaseData.Builder.class);
      }

    public static com.google.protobuf.Parser<BaseData> PARSER =
        new com.google.protobuf.AbstractParser<BaseData>() {
            @Override
            public BaseData parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new BaseData(input, extensionRegistry);
            }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BaseData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     */
    @Override
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     */
    @Override
    public int getCode() {
      return code_;
    }

    private void initFields() {
      code_ = 0;
    }
    private byte memoizedIsInitialized = -1;

      @Override
      public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) {
              return isInitialized == 1;
          }

          if (!hasCode()) {
              memoizedIsInitialized = 0;
              return false;
          }
          if (!extensionsAreInitialized()) {
              memoizedIsInitialized = 0;
              return false;
          }
          memoizedIsInitialized = 1;
          return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
          getSerializedSize();
          com.google.protobuf.GeneratedMessage
                  .ExtendableMessage<Example.BaseData>.ExtensionWriter extensionWriter =
                  newExtensionWriter();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
              output.writeInt32(1, code_);
          }
          extensionWriter.writeUntil(200, output);
          getUnknownFields().writeTo(output);
      }

    private int memoizedSerializedSize = -1;

      @Override
      public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) {
              return size;
          }

          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
              size += com.google.protobuf.CodedOutputStream
                      .computeInt32Size(1, code_);
          }
          size += extensionsSerializedSize();
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
      }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Example.BaseData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.BaseData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.BaseData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.BaseData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.BaseData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Example.BaseData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Example.BaseData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Example.BaseData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Example.BaseData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Example.BaseData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Example.BaseData prototype) {
      return newBuilder().mergeFrom(prototype);
    }

      @Override
      public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseData}
     *
     * <pre>
     * ����һ��message BaseData��100~199֮���tag�ɹ���չ  
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          Example.BaseData, Builder> implements Example.BaseDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Example.internal_static_BaseData_descriptor;
      }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Example.internal_static_BaseData_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Example.BaseData.class, Example.BaseData.Builder.class);
        }

      // Construct using Example.BaseData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

        @Override
        public Builder clear() {
            super.clear();
            code_ = 0;
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
        }

        @Override
        public Builder clone() {
            return create().mergeFrom(buildPartial());
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Example.internal_static_BaseData_descriptor;
        }

        @Override
        public Example.BaseData getDefaultInstanceForType() {
            return Example.BaseData.getDefaultInstance();
        }

        @Override
        public Example.BaseData build() {
            Example.BaseData result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public Example.BaseData buildPartial() {
            Example.BaseData result = new Example.BaseData(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                to_bitField0_ |= 0x00000001;
            }
            result.code_ = code_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Example.BaseData) {
                return mergeFrom((Example.BaseData)other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

      public Builder mergeFrom(Example.BaseData other) {
          if (other == Example.BaseData.getDefaultInstance()) {
              return this;
          }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

        @Override
        public final boolean isInitialized() {
            if (!hasCode()) {

                return false;
            }
            if (!extensionsAreInitialized()) {

                return false;
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Example.BaseData parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Example.BaseData) e.getUnfinishedMessage();
                throw e;
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }
      private int bitField0_;

      // required int32 code = 1;
      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       */
      @Override
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      @Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BaseData)
    }

    static {
      defaultInstance = new BaseData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BaseData)
  }

  public static final int EXTEND_DATA_FIELD_NUMBER = 100;
  /**
   * <code>extend .BaseData { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      Example.BaseData,
      java.lang.String> extendData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rExample.proto\"\037\n\010BaseData\022\014\n\004code\030\001 \002(" +
      "\005*\005\010d\020\310\001:\036\n\013extend_data\022\t.BaseData\030d \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          @Override
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
                  com.google.protobuf.Descriptors.FileDescriptor root) {
              descriptor = root;
              internal_static_BaseData_descriptor =
                      getDescriptor().getMessageTypes().get(0);
              internal_static_BaseData_fieldAccessorTable = new
                      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                      internal_static_BaseData_descriptor,
                      new java.lang.String[] { "Code", });
              extendData.internalInit(descriptor.getExtensions().get(0));
              return null;
          }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
