spring:
  datasource:
    url: jdbc:mysql://localhost/jpa_onetomany
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true